/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.apptest;

import org.openqa.selenium.WebDriver;

import com.apptest.utils.DriverFactory;

import io.cucumber.java.After;
import io.cucumber.java.Before;

public class PaybackAppBase {

	WebDriver driver;

	@Before
	public void setUp() {

		driver = DriverFactory.createDriverInstance();

	}

	@After
	public void tearDown() {

		DriverFactory.stopDriver();

	}
	
	

}
